# Exporta os traces via OTLP (padrão OpenTelemetry)
quarkus.opentelemetry.tracer.exporter.otlp.endpoint=http://otel-collector:4317
# Kafka
mp.messaging.outgoing.users-events.bootstrap.servers=kafka:9092
mp.messaging.outgoing.users-events.topic=users-events
mp.messaging.outgoing.users-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer
