# otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  # Exporta traces para Grafana Tempo
  otlp/tempo:
    endpoint: http://tempo:4317
    tls:
      insecure: true

  # Exporta métricas para Grafana Mimir
  prometheusremotewrite/mimir:
    endpoint: http://mimir:9009/api/v1/push

  # Exporta logs para Grafana Loki
  loki:
    endpoint: http://loki:3100/loki/api/v1/push

processors:
  batch:

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite/mimir]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
